In [2]:
import pandas as pd
claim = pd.read_csv("output_data/claim.csv")
condition = pd.read_csv("output_data/condition.csv")
encounter = pd.read_csv("output_data/encounter.csv")
medicationrequest = pd.read_csv("output_data/medicationrequest.csv")
observation = pd.read_csv("output_data/observation.csv")
patient = pd.read_csv("output_data/patient.csv")
procedure = pd.read_csv("output_data/procedure.csv") 

claim.head()

,claim_id,patient_id,encounter_id,status,claim_type,created_date,provider_name,payer,total_amount,currency,service_code,service_desc
0,15f05361-dede-0d32-7e8b-455048db7f34,b0a06ead-cc42-aa48-dad6-841d4aa679fa,a889805b-20ca-0ba6-5b5c-e617ce99b0cc,active,institutional,1954-04-03T12:29:47-05:00,MOUNT AUBURN HOSPITAL,UnitedHealthcare,77.49,USD,185347001,Encounter for problem
1,e435aaad-5d5c-bca6-7a3b-1aba157e01da,b0a06ead-cc42-aa48-dad6-841d4aa679fa,b1ca5d4d-e3b5-e65b-e900-3844ae30f421,active,institutional,1954-04-20T08:29:47-05:00,MOUNT AUBURN HOSPITAL,UnitedHealthcare,77.49,USD,185347001,Encounter for problem
2,75c45f6c-bb5a-e92d-0cc2-af28a0516767,b0a06ead-cc42-aa48-dad6-841d4aa679fa,853a4e65-da0d-d531-eb6e-458a70bcf552,active,institutional,1959-06-03T15:33:08-04:00,MOUNT AUBURN HOSPITAL,UnitedHealthcare,624.90,USD,185345009,Encounter for symptom
3,4244b2dc-9a09-b63e-1ad8-c7dd8a59be98,b0a06ead-cc42-aa48-dad6-841d4aa679fa,b04db379-2092-c969-8968-39ab3557b605,active,institutional,1971-01-29T03:29:47-05:00,PCP58532,Aetna,1241.42,USD,162673000,General examination of patient (procedure)
4,78d012c9-0b85-c1ba-abb7-ee76c10f19b5,b0a06ead-cc42-aa48-dad6-841d4aa679fa,dffdcaf9-384a-3472-867c-2f852dc61851,active,institutional,1977-10-25T04:29:47-04:00,MOUNT AUBURN HOSPITAL,Humana,5850.25,USD,185345009,Encounter for symptom

In [3]:
condition.head()

,condition_id,patient_id,encounter_id,clinical_status,condition_code,condition_system,condition_name,onset_date,recorded_date
0,8695c578-79e7-b7fa-0d3b-be91b95d4a56,b0a06ead-cc42-aa48-dad6-841d4aa679fa,b04db379-2092-c969-8968-39ab3557b605,active,224299000,http://snomed.info/sct,Received higher education (finding),1971-01-29T04:04:48-05:00,1971-01-29T04:04:48-05:00
1,2f9b9ad8-6dd5-b94b-e7e7-d329d204cedb,b0a06ead-cc42-aa48-dad6-841d4aa679fa,b04db379-2092-c969-8968-39ab3557b605,resolved,160903007,http://snomed.info/sct,Full-time employment (finding),1971-01-29T04:04:48-05:00,1971-01-29T04:04:48-05:00
2,c21907ce-d314-d9ac-87b5-e9dff5371c13,b0a06ead-cc42-aa48-dad6-841d4aa679fa,ed03c4f1-9865-7638-37d1-d7c1fe282363,resolved,160903007,http://snomed.info/sct,Full-time employment (finding),1978-02-10T03:45:33-05:00,1978-02-10T03:45:33-05:00
3,896c3120-7689-0630-2698-04d5a3f5f704,b0a06ead-cc42-aa48-dad6-841d4aa679fa,e756ebcd-40d3-59f6-257c-4b413d4e94e8,resolved,160903007,http://snomed.info/sct,Full-time employment (finding),1981-02-13T04:03:53-05:00,1981-02-13T04:03:53-05:00
4,204b175e-3004-a395-0d11-cc2123bebd43,b0a06ead-cc42-aa48-dad6-841d4aa679fa,e44915f6-9666-521e-7c74-6f5a5035db88,resolved,160903007,http://snomed.info/sct,Full-time employment (finding),1984-02-17T03:47:12-05:00,1984-02-17T03:47:12-05:00

In [4]:
encounter.head()

,encounter_id,patient_id,status,class_code,encounter_type,start_date,end_date,provider_name,practitioner
0,a889805b-20ca-0ba6-5b5c-e617ce99b0cc,b0a06ead-cc42-aa48-dad6-841d4aa679fa,finished,AMB,Encounter for problem,1954-04-03T12:14:47-05:00,1954-04-03T12:29:47-05:00,MOUNT AUBURN HOSPITAL,Dr. Lesley194 Fisher429
1,b1ca5d4d-e3b5-e65b-e900-3844ae30f421,b0a06ead-cc42-aa48-dad6-841d4aa679fa,finished,AMB,Encounter for problem,1954-04-20T08:14:47-05:00,1954-04-20T08:29:47-05:00,MOUNT AUBURN HOSPITAL,Dr. Lesley194 Fisher429
2,853a4e65-da0d-d531-eb6e-458a70bcf552,b0a06ead-cc42-aa48-dad6-841d4aa679fa,finished,AMB,Encounter for symptom,1959-06-03T15:14:47-04:00,1959-06-03T15:33:08-04:00,MOUNT AUBURN HOSPITAL,Dr. Lesley194 Fisher429
3,b04db379-2092-c969-8968-39ab3557b605,b0a06ead-cc42-aa48-dad6-841d4aa679fa,finished,AMB,General examination of patient (procedure),1971-01-29T03:14:47-05:00,1971-01-29T03:29:47-05:00,PCP58532,Dr. Sommer719 Hilpert278
4,dffdcaf9-384a-3472-867c-2f852dc61851,b0a06ead-cc42-aa48-dad6-841d4aa679fa,finished,AMB,Encounter for symptom,1977-10-25T04:14:47-04:00,1977-10-25T04:29:47-04:00,MOUNT AUBURN HOSPITAL,Dr. Lesley194 Fisher429

In [5]:
medicationrequest.head()

,medication_id,patient_id,encounter_id,status,intent,medication_code,medication_name,authored_date,requester
0,c0e50da8-7aed-f2db-f893-efe740504150,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,stopped,order,312961.0,Simvastatin 20 MG Oral Tablet,1992-04-10T04:14:47-04:00,Dr. Lesley194 Fisher429
1,28fe47d9-82cf-c35d-468d-39ecd61c3b9c,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,stopped,order,705129.0,Nitroglycerin 0.4 MG/ACTUAT Mucosal Spray,1992-04-10T04:14:47-04:00,Dr. Lesley194 Fisher429
2,4d93f56b-3db5-e0a6-a4c7-f65cf2b8538d,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,stopped,order,705129.0,Nitroglycerin 0.4 MG/ACTUAT Mucosal Spray,1992-04-10T04:14:47-04:00,Dr. Lesley194 Fisher429
3,9f5c47fb-b639-e236-ea1a-b6bc2fcab325,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,stopped,order,312961.0,Simvastatin 20 MG Oral Tablet,1992-04-10T04:14:47-04:00,Dr. Lesley194 Fisher429
4,e7a52e7d-d8ec-5824-b4a6-bb936b2f299a,b0a06ead-cc42-aa48-dad6-841d4aa679fa,f2f337b4-33bb-1fe1-4f96-8102f9a8b75a,stopped,order,705129.0,Nitroglycerin 0.4 MG/ACTUAT Mucosal Spray,1992-04-24T04:14:47-04:00,Dr. Sommer719 Hilpert278

In [6]:
patient.head()

,patient_id,first_name,last_name,gender,birth_date,race,ethnicity,birth_place,city,state,postal_code,country,marital_status,language
0,b0a06ead-cc42-aa48-dad6-841d4aa679fa,Abdul218,Harris789,male,1952-12-05,Black or African American,Not Hispanic or Latino,"Boston, Massachusetts",Boston,MA,2134.0,US,M,English
1,ccfc4db2-2026-7adb-3db0-33f3828140bb,Abe604,Schmidt332,male,1976-06-06,White,Not Hispanic or Latino,"Worcester, Massachusetts",Peabody,MA,1940.0,US,M,English
2,31a2e8ec-69fc-8a71-3ab6-36cbdd508713,Adelaida985,DuBuque211,female,1917-05-15,White,Not Hispanic or Latino,"Boston, Massachusetts",Quincy,MA,2169.0,US,M,English
3,71a8b156-760b-df6b-859e-eefc7932a526,Adriana394,Hintz995,female,2014-11-15,White,Not Hispanic or Latino,"Amherst Center, Massachusetts",Boston,MA,2120.0,US,Never Married,English
4,76b289fd-e825-734c-8446-316f59643593,Agueda283,Gerhold939,female,1985-03-03,White,Not Hispanic or Latino,"Weymouth, Massachusetts",Boston,MA,2115.0,US,M,English

In [7]:
observation.head()

,observation_id,patient_id,encounter_id,status,obs_code,obs_system,obs_name,effective_date,value,unit
0,33648be3-5286-a324-312c-c9cf3cfedac8,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,final,8302-2,http://loinc.org,Body Height,1992-04-10T04:14:47-04:00,186,cm
1,a5cd0f82-45c2-1f1c-b5cb-24d317cfa74b,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,final,72514-3,http://loinc.org,Pain severity - 0-10 verbal numeric rating [Sc...,1992-04-10T04:14:47-04:00,1,{score}
2,75a7476a-de6c-ce31-5b47-e5e72e7c4211,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,final,29463-7,http://loinc.org,Body Weight,1992-04-10T04:14:47-04:00,102.8,kg
3,26945d93-ed09-2c27-55d2-698657b29dcf,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,final,39156-5,http://loinc.org,Body Mass Index,1992-04-10T04:14:47-04:00,29.71,kg/m2
4,fa2b75e0-a7aa-5fdb-34d8-c88c3addc246,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,final,85354-9,http://loinc.org,Blood Pressure,1992-04-10T04:14:47-04:00,NaN,NaN

In [8]:
procedure.head()

,procedure_id,patient_id,encounter_id,status,procedure_code,procedure_system,procedure_name,performed_start,performed_end
0,c552f97a-c15d-2093-458d-ceab8d7baeba,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,completed,710824005,http://snomed.info/sct,Assessment of health and social care needs (pr...,1992-04-10T04:14:47-04:00,1992-04-10T05:04:36-04:00
1,49d55c87-ed5c-e8a5-420a-ab735747d2c6,b0a06ead-cc42-aa48-dad6-841d4aa679fa,d331b9e7-cc03-6a74-ecac-64fedddb57a9,completed,430193006,http://snomed.info/sct,Medication Reconciliation (procedure),1992-04-10T04:14:47-04:00,1992-04-10T04:29:47-04:00
2,be2a8430-0cbf-de54-cd72-ca28bb0266e9,b0a06ead-cc42-aa48-dad6-841d4aa679fa,6afb13cd-d1c9-d1ac-5524-6b939b91ada4,completed,710841007,http://snomed.info/sct,Assessment of anxiety (procedure),1992-04-10T05:04:36-04:00,1992-04-10T05:22:25-04:00
3,b02eaa77-e8c4-2ff3-a8f3-e2823b5872ee,b0a06ead-cc42-aa48-dad6-841d4aa679fa,6afb13cd-d1c9-d1ac-5524-6b939b91ada4,completed,866148006,http://snomed.info/sct,Screening for domestic abuse (procedure),1992-04-10T05:22:25-04:00,1992-04-10T05:51:19-04:00
4,a3511024-929f-d337-1a37-0ad20429a08d,b0a06ead-cc42-aa48-dad6-841d4aa679fa,6afb13cd-d1c9-d1ac-5524-6b939b91ada4,completed,171207006,http://snomed.info/sct,Depression screening (procedure),1992-04-10T05:51:19-04:00,1992-04-10T06:01:59-04:00

In [17]:
procedure.columns

Index(['procedure_id', 'patient_id', 'encounter_id', 'status',
       'procedure_code', 'procedure_system', 'procedure_name',
       'performed_start', 'performed_end'],
      dtype='str')